### ISSUE TITLE
VPS Training dataset problem

### ISSUE THREAD

**Issue by rscr1** [zju3dv/PVO#16]
I am trying to train a VPS module using config file from guide (`VPS_Module/configs/COCO-PanopticSegmentation/panoptic_fpn_R_50_3x_vkitti_511.yaml`). And it contains
```yaml
DATASETS:
  TRAIN: ("vkitti_511_train",)
  TEST: ("vkitti_511_val",)
```
But `VPS_Module/detectron2/data/datasets/others.py` doesn't contain `vkitti_511_train`
```py
def register_others(root):
    register_vkitti_511_val()
    register_vkitti_clone()
    register_vkitti_test()
```

How i can fix this problem? thx
